# Generated by Django 5.0.1 on 2024-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('expected_return', models.FloatField()),
                ('volatility', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('risk_free_rate', models.FloatField()),
            ],
        ),
    ]
