# Generated by Django 4.1.13 on 2024-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AY', models.IntegerField()),
                ('Regime', models.CharField(max_length=20)),
                ('SalaryDA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HRAReceived', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OtherAllowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LessAllowancesu10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProfessionalTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StandardDeduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SelfOccupiedInterestonHouLoan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RentReceived', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PropertyTax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RentedHousePropertyInterestonHouLoan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RepairCharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Business', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Profession', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SavingInterest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FDInterest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DividendIncome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OtherIncome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthLIC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthProvidendFund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthPPF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthHousingLoanRepayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthNPS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthELLS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthTutionFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthOthers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthDSelf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthDParents', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthDD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthDDB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthCCDoneB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthCCDtwo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthEEA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthFFB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthGfiftypercent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthGhundredpercent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthGGA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthGGC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthTTA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eighthTTB', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
