# Generated by Django 4.1.13 on 2024-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('macd', models.FloatField()),
                ('signal', models.FloatField()),
                ('atr', models.FloatField()),
                ('mb', models.FloatField()),
                ('ub', models.FloatField()),
                ('lb', models.FloatField()),
                ('bb_width', models.FloatField()),
                ('rsi', models.FloatField()),
            ],
        ),
    ]
